version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:860061945305:task-definition/return851334:1"
        LoadBalancerInfo:
          ContainerName: "paymentservice"
          ContainerPort: "9004"
        PlatformVersion: "LATEST"
